# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

env:
  NODE_VERSION: '16.x'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: Setup Edge and EdgeDriver
        uses: ./.github/actions/setup-edge
      - name: Start XVFB
        run: Xvfb :99 &
      - name:
        run: |
          echo "Hello World!""
        env:
          DISPLAY: :99
