name: Manual workflow 3

on:
  workflow_dispatch:
    inputs:
      msg:
        description: 'Message'
        default: 'Hello'

env:
  NODE_VERSION: '16.x'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # - name: Setup Edge and EdgeDriver
    #   uses: ./.github/actions/setup-edge
    # - name: Start XVFB
    #   run: Xvfb :99 &
      - name: Test
        run: |
          echo "Hello World!""
        # env:
        #   DISPLAY: :99